name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libboost-test-dev

    - name: Clean CMake build cache
      run: rm -rf build
      shell: bash

    - name: Configure CMake
      run: cmake -S . -B build
      shell: bash

    - name: Build the project
      run: cmake --build build
      shell: bash

    - name: Run tests
      run: ctest --test-dir build
      shell: bash