name: 'C++ CI'  # Название рабочего процесса

on:
  push:  # Запускает процесс при событии push
    branches:
      - main  # Для ветки main
      - feature/github_actions  # Для веток с названием feature/github_actions

permissions:              
  contents: write  # Права на запись в репозиторий

jobs:
  build:  # Определение задачи сборки
    strategy:
      matrix:  # Использует матрицу для запуска на нескольких ОС
        os: [ubuntu-latest, macos-latest]  # Указывает, что задача будет выполняться на Ubuntu и macOS
    runs-on: ${{ matrix.os }}  # Запускает задачу на ОС, указанной в матрице
    steps:  # Шаги выполнения задачи
      - uses: actions/checkout@v3  # Проверяет код репозитория

      - name: Install dependencies on Linux  # Установка зависимостей для Linux
        if: ${{ runner.os == 'Linux' }}  
        run: |  
          sudo apt-get update  
          sudo apt-get install -y libboost-test-dev cmake g++  

      - name: Install dependencies on macOS  # Установка зависимостей для macOS
        if: ${{ runner.os == 'macOS' }}  
        run: |  
          brew update  
          brew install boost cmake  

      - name: Configure with CMake  # Конфигурация проекта с помощью CMake
        run: |  
          cmake .  

      - name: Build the project  # Сборка проекта
        run: |  
          cmake --build . --config Release  

      - name: Run tests  # Запуск тестов проекта
        run: |  
          cmake --build . --target test  

      - name: Create package  # Создание пакета для распространения
        run: |  
          cmake --build . --target package  

      - name: Create Release for Linux  
        if: ${{ runner.os == 'Linux' }}  
        id: create_release_linux  
        uses: actions/create-release@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          tag_name: "linux-${{ github.run_number }}"  
          release_name: "Release Linux ${{ github.run_number }}"  
          draft: false  
          prerelease: false  

      - name: Upload Release Asset (Linux)  
        if: ${{ runner.os == 'Linux' }}  
        uses: actions/upload-release-asset@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}  
          asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb  
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb  
          asset_content_type: application/vnd.debian.binary-package  

      - name: Create Release for macOS  
        if: ${{ runner.os == 'macOS' }}  
        id: create_release_macos   
        uses: actions/create-release@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          tag_name: "macos-${{ github.run_number }}"   
          release_name: "Release macOS ${{ github.run_number }}"  
          draft: false   
          prerelease: false  

      - name: Upload Release Asset (macOS)  
        if: ${{ runner.os == 'macOS' }}  
        uses: actions/upload-release-asset@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}  
          asset_path: ./helloworld-0.0.${{ github.run_number }}-Darwin.dmg  
          asset_name: helloworld-0.0.${{ github.run_number }}-Darwin.dmg  
          asset_content_type: application/x-apple-diskimage   