name: IPFilterProject

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest

      - name: Create release
        uses: actions/upload-artifact@v2
        with:
          name: ip_filter
          path: build/ip_filter

  build-and-test-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install cmake boost

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest

      - name: Create release
        uses: actions/upload-artifact@v2
        with:
          name: ip_filter
          path: build/ip_filter